# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.1.29

pipelines:
  custom:
    deployment-to-kube:
      - step:
          name: 'Deploy to Kube Prod'
          script:
            - apt update && apt install -y openssh-client

    deployment-to-aws-prod:
      - step:
          name: 'Deploy to AWS Prod'
          script:
            - apt update && apt install -y openssh-client
            - ssh bitbucket@$AWS_PROD_IP "sudo -s bash /var/www/html/mass-house-main-site/bin/deploy.sh $AWS_PROD_FORM_URL"
  branches:
    staging:
      - step:
          name: 'Deploy to Staging'
          script:
            - apt update && apt install -y openssh-client
            - ssh bitbucket@$ETAX_DEV_IP "sudo -s bash /var/www/html/mass-house-main-site/bin/deploy.sh $STAGING_FORM_URL staging"
