# Default values for mass-housing-main.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 8

strategy:
  type: RollingUpdate
  rollingUpdate:
    # number of pods to be added per time.
    maxSurge: 2
    # number of pods to be unavailable during a rolling update.
    maxUnavailable: 0

image:
    repository: eu.gcr.io/nqlb-207716/mass-housing-main-master
    tag: latest
    pullPolicy: Always

imagePullSecrets: []
nameOverride: 'mass-housing-main'
fullnameOverride: 'mass-housing-main'

valueFrom:
    secretKeyRef:
        name: mass-housing-main-secrets

service:
    type: NodePort
    http_port: 80

ingress:
    enabled: false
    annotations:
        {}
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
    hosts:
        - host: #TODO add host
          paths:
              - backend:
                serviceName: mass-housing-main
                servicePort: 4020

    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

resources:
    {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
